version: 0.0
os: linux
files:
  - source: published/
    destination: /home/ec2-user/MyDotNetApp
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
  ApplicationStart:
    - location: scripts/start_server.sh
  ApplicationStop:
    - location: scripts/stop_server.sh