version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
  build:
    commands:
      - dotnet publish -c Release -o published/
      - Compress-Archive -Path appspec.yml, scripts, published -DestinationPath MyDotNetAppBundle.zip

artifacts:
  files:
    - MyDotNetAppBundle.zip