version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo Installing .NET dependencies...
  build:
    commands:
      - dotnet publish -c Release -o published

artifacts:
  files:
    - published/**/*
