version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Installing zip utility..."
      - yum install -y zip
  build:
    commands:
      - dotnet publish -c Release -o published/

artifacts:
  files:
    - appspec.yml
    - published/**/* 
    - scripts/**/* 
  discard-paths: no
post_build:
  commands:
    - echo "Listing files in build root:"
    - ls -al