version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Building the project...
      - dotnet build
  post_build:
    commands:
      - echo Publishing the project...
      - dotnet publish -c Release -o published/

artifacts:
  files:
    - published/**/*
